spring:
  application:
    name: scrabble-points-calculator
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:scrabble_db}
    username: ${DB_USER:scrabble_user}
    password: ${DB_PASSWORD:scrabble_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  web:
    cors:
      allowed-origins: "http://localhost:${FRONTEND_PORT:3000}"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    "[com.scrabble.calculator]": DEBUG
    "[com.scrabble.logging]": INFO
    "[org.springframework.web]": DEBUG
    "[org.hibernate.SQL]": DEBUG
